return {PluginComponents = script.PluginComponents, StudioComponents = script.StudioComponents}

-- TODO: 
-- Merge some of the features that Efe has made, and clean-up certain modules to allow them to work easier.
-- Make a global (and better) types module that will contain the component type for every component. (Finish up from Background until all modules are updated.)
-- Using the Class++ documentation design, create a documentation for PluginComponents with images.