name: Build Documentation with MkDocs
on:
  push:
    branches:
      - main

env:
  Version: '1.2.0'
  Deploy_Type: 'release'

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: List files in the repository
        run: ls -la

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install necessary tools
        run: | 
          pip install mkdocs-material
          pip install pillow cairosvg
          pip install --upgrade setuptools
          pip install mike

      - name: Configure the git user
        run: |
          git config user.name pedoc
          git config user.email pedoc@example.com

      - name: Clear gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          rm -rf *
          git add .
          git commit -m "Clear gh-pages for new deployment" || echo "No changes to commit"
          git push origin gh-pages

      - name: Build documentation
        run: mkdocs build

      - name: Deploy latest documentation version
        if: env.Deploy_Type == 'release'
        run: |
          mike deploy $Version latest --update-aliases --branch gh-pages

      - name: Set default version to latest
        if: env.Deploy_Type == 'release'
        run: mike set-default latest --branch gh-pages 